services:
    postgis: 
        container_name: postgis
        image: postgis
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - .env
        ports: 
            - "4322:5432"
        volumes: 
            - postgis_data:/var/lib/postgresql
            - ./init:/docker-entrypoint-initdb.d:ro
        command: ["postgres",
            "-c", "max_wal_size=8GB",
            "-c", "min_wal_size=512MB",
            "-c", "wal_compression=on",
            "-c", "checkpoint_timeout=5min",
            "-c", "checkpoint_completion_target=0.6"
            ]
    osm2pgsql:
        depends_on:
            postgis:
                condition: service_healthy
        image: osm2pgsql
        build:
            context: .
            dockerfile: ./osm2pgsql.Dockerfile
        env_file:
            - .env
        environment:
            - PGPASSWORD=${POSTGRES_PASSWORD}
        entrypoint:
            - bash
            - -lc
        command:
            - "./scr/osm"
        volumes:
            - ./osm:/data:ro
            - ./scr:/scr:ro
    acs2024_restore:
        image: postgres:18
        depends_on:
            postgis:
                condition: service_healthy
        env_file:
            - .env
        environment:
            - PGHOST=postgis
            - PGPORT=5432
            - PGUSER=${POSTGRES_USER}
            - PGPASSWORD=${POSTGRES_PASSWORD}
            - PGDATABASE=${POSTGRES_DB}
        volumes:
            - ./acs24_5:/census_upload
            - ./scr/acs:/scr/acs:ro
        command:
            - bash 
            - -lc
            - |
                /scr/acs

    tiger:
        image: ghcr.io/osgeo/gdal:alpine-small-latest
        depends_on:
            postgis:
                condition: service_healthy
        env_file:
            - .env
        environment:
            - PGHOST=postgis
            - PGPORT=5432
            - PGUSER=${POSTGRES_USER}
            - PGPASSWORD=${POSTGRES_PASSWORD}
            - PGDATABASE=${POSTGRES_DB}
        volumes:
            - ./tiger24:/tiger
            - ./scr/tgr:/scr/tgr:ro
        command:
            - sh
            - -lc
            - |
                /scr/tgr
    pg_backup:
        image: postgres:18
        depends_on:
            postgis:
                condition: service_healthy
        env_file:
            - .env
        environment:
            - PGHOST=postgis
            - PGPORT=5432
            - PGUSER=${POSTGRES_USER}
            - PGPASSWORD=${POSTGRES_PASSWORD}
            - PGDATABASE=${POSTGRES_DB}
        volumes:
            - ./dump:/dump
        command:
            - bash
            - -lc
            - |
                /scr/bkp:/scr/bkp:ro
volumes:
    postgis_data: