services:
    postgis: 
        container_name: postgis
        image: postgis
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - .env
        ports: 
            - "4322:5432"
        volumes: 
            - postgis_data:/var/lib/postgresql
            - ./init:/docker-entrypoint-initdb.d:ro
            - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
        command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    osm:
        container_name: fetch-osm
        depends_on:
            postgis:
                condition: service_healthy
        image: fetch-osm
        build:
            context: .
            dockerfile: ./osm.Dockerfile
        env_file:
            - .env
        volumes:
            - ./osm:/data:ro
            - ./scr/osm:/scr/osm:ro
        entrypoint: [ "/scr/osm" ]
    acs:
        container_name: fetch-acs
        depends_on:
            postgis:
                condition: service_healthy
        image: postgres:18
        env_file:
            - .env
        volumes:
            - ./acs24_5:/census_upload
            - ./scr/acs:/scr/acs:ro
        entrypoint: [ "/scr/acs"]
    tgr:
        container_name: fetch-tiger
        image: ghcr.io/osgeo/gdal:alpine-small-latest
        depends_on:
            postgis:
                condition: service_healthy
        env_file:
            - .env
        volumes:
            - ./tiger24:/tiger
            - ./scr/tgr:/scr/tgr:ro
        entrypoint: [ "/scr/tgr" ]
    pg_backup:
        image: postgres:18
        depends_on:
            postgis:
                condition: service_healthy
        env_file:
            - .env
        volumes:
            - ./dump:/dump
            - ./scr/bkp:/scr/bkp:ro
        entrypoint: [ "/scr/bkp"]
volumes:
    postgis_data: