#!/usr/bin/env bash

# def
REGION="us-northeast"
URL="https://download.geofabrik.de/north-america/$REGION-latest.osm.pbf"
PGHOST=postgis
PGPORT=5432
MODE=append
tmp=/tmp/in.osm.pbf

# cmd
set -euo pipefail

curl -L --fail --retry 10 --retry-delay 2 --retry-all-errors "$URL" -o "$tmp"

osm2pgsql -v -r pbf -H "$PGHOST" -P "$PGPORT" -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" \
    --"$MODE" --slim --hstore --cache 4096 \
    "$tmp"