#!/usr/bin/env bash

# def
SCHEMA="tgr24"
DIR="census_upload"
DUMP="acs2024_5yr_backup.sql.gz"
URL="https://backup.censusreporter.org/census-reporter-extracts/acs2024_5yr_backup.sql.gz"

declare -A TGR_FILES
TGR_FILES["tl_2024_us_state.zip"]="STATE"
TGR_FILES["tl_2024_us_county.zip"]="COUNTY"
TGR_FILES["tl_2024_29_tract.zip"]="TRACT"
TGR_FILES["tl_2024_17_tract.zip"]="TRACT"

# cmd
set -euo pipefail

apk add --no-cache curl unzip postgresql-client



for key in "${!TGR_SHPFILES[@]}"; do
    curl -L --fail --retry 10 --retry-delay 2 -o $key \
        "https://www2.census.gov/geo/tiger/TIGER2024/${TGR_SHPFILES[$key]}/$key"
done